# Anytime we use docker, we need to require sudo permissions:
sudo: required
services:
    - docker

before_install:
  - docker build -t rhysgoehring/docker-react -f Dockerfile.dev .

script:
   - docker run rhysgoehring/docker-react npm run test -- --coverage
